version: "3"
services:
    queue-api:
        container_name: queue-api
        build:
            context: ./queue-api
            no_cache: true
        command: yarn start
        env_file:
            - ./dev-auto.env
        volumes:
            - ./queue-api:/usr/src/queue-api
        ports:
            - "3006:3006"
    main-api:
        container_name: main-api
        build:
            context: ./main-api
            no_cache: true
        command: yarn start
        env_file:
            - ./dev-auto.env
        volumes:
            - ./main-api:/usr/src/main-api
        ports:
            - "3005:3005"

    

  